### ISSUE TITLE
Feature: Security Policy

### ISSUE THREAD

**Issue by eslerm** [ubuntu/authd#200]
Please add a `SECURITY.md` as to define authd's Security Policy.

The primary purpose of a Security Policy is to tell researchers how to privately report issues to authd. `SECURITY.md` is the standard place to write the policy and will be displayed on https://github.com/ubuntu/authd/security 

It's great that the Issue template also includes a reporting policy! That text asks that vulnerabilities should be reported on Launchpad. Please specify that security issues should be reported on Launchpad using the "This bug is a security vulnerability" option, otherwise the bug will not be private.

[LXD](https://github.com/canonical/lxd/security) and [GitHub](https://securitylab.github.com/advisories/#policy) have great examples. Happy to review.

**Comment by jibel** [comment]
Thanks for your report. The policy is documented in PR #521 and the vulnerability reporting feature has been enabled.
