### ISSUE TITLE
TestClear/Error_when_cache_dir_has_invalid_permissions is failing when building the deb

### ISSUE THREAD

**Issue by 3v1n0** [ubuntu/authd#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

```
=== NAME  TestClear/Error_when_cache_dir_has_invalid_permissions
    db_test.go:460: 
        	Error Trace:	/build/authd-8HIczg/authd-0.2.2~gdm1/obj-x86_64-linux-gnu/src/github.com/ubuntu/authd/internal/users/cache/db_test.go:460
        	Error:      	An error is expected but got nil.
        	Test:       	TestClear/Error_when_cache_dir_has_invalid_permissions
        	Messages:   	Clear should return an error but didn't
```

### Steps to reproduce it

1. Just build the deb

### Relevant information

Eh... If we had #130 active we wouldn't have missed it... :)

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by 3v1n0** [comment]
@denisonbarbosa I guess you can handle this :)

**Comment by 3v1n0** [comment]
At least one seems to be skippable:

```diff
diff --git a/debian/control b/debian/control
index f808322..a9fb004 100644
--- a/debian/control
+++ b/debian/control
@@ -452,6 +452,11 @@ func TestClear(t *testing.T) {
 				require.NoError(t, os.Remove(c.DbPath()), "Setup: should be able to remove database file")
 			}
 			if tc.readOnlyDir {
+				currentUser, err := user.Current()
+				require.NoError(t, err)
+				if currentUser.Username == "root" {
+					t.Skip("Can't do permission checks as root")
+				}
 				testutils.MakeReadOnly(t, filepath.Dir(c.DbPath()))
 			}
 
```

**Comment by denisonbarbosa** [comment]
The package builds normally for me and [on launchpad as well](https://launchpad.net/~justdenis/+archive/ubuntu/authd). My question is: why are you building the deb as sudo?

**Comment by denisonbarbosa** [comment]
> this is the error that you get when building it via [sbuild](https://manpages.debian.org/buster/sbuild/sbuild.1.en.html)

That's the kind of thing that should be listed on `Relevant Information`... :wink:  

Also, most of the tutorials and packaging documentation suggest using `debuild` to build the packages, so I'm a bit sceptical about the `most ubuntu/debian developers do to build packages` sentence. 

My point is that if we try to cover "all" of the possible tools/ways to build the package, we could end up with a lot of code only to support a specific occurrence, which is not great.

In the team, we use `gbp` to build the packages (I'm not sure it's documented anywhere, so that's our bad, we should have it written down somewhere) and the permissions tests are essential.

**Comment by 3v1n0** [comment]
I suggest you to document a bit better ;-) on packaging, but in short, you should _never_ (unless for tiny packages or for frequent rebuilds), build a package in the local environment because that affects a lot the build process making the whole process flawed.

To prevent this, and to make sure that a package has all the required components in depends & friends, one should build the package in a clean environment, and that's where `schroot` helps you and `sbuild` does nothing but calling `dpkg-buldpackage` inside a such clean environment. So, please use it :).

> In the team, we use `gbp` to build the packages (I'm not sure it's documented anywhere, so that's our bad, we should have it written down somewhere) and the permissions tests are essential.

We documented it [various years ago](https://wiki.ubuntu.com/DesktopTeam/git). And I do use gbp to generate the source packages too, but eventually it's `sbuild` that is used to build it in a clean environment. You can also use lxd, but it's harder to maintain.

**Comment by 3v1n0** [comment]
This page has also some quick infos: https://debian-handbook.info/browse/stable/debian-packaging.html
