### ISSUE TITLE
Issue: Only load broker config files based on extension

### ISSUE THREAD

**Issue by 3v1n0** [ubuntu/authd#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

We just load any file that is in `/etc/authd/brokers.d/` but this could be a problem when dpkg updates may lead files in that files (e.g. `*.dpkg-old` ones), so it's safer to just load files `*.conf`.

### Steps to reproduce it

.

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by didrocks** [comment]
This is now fixed and merged.
