### ISSUE TITLE
Feature: Consider loading broker config files from /usr/{share,lib}/authd/brokers.d/

### ISSUE THREAD

**Issue by 3v1n0** [ubuntu/authd#227]
### Is there an existing request for this feature?

- [X] I have searched the existing issues and found none that matched mine

### Describe the feature

`/etc` is a very special thing in debian-based systems and storing files there implies that those may not be removed on package removal unless purge is done.

This may be a problem in authd because we still list the broker as installed even though it's not there anymore.

### Describe the ideal solution

While authd maybe could do some better sanity check on available brokers in the bus, it's probably better to use other paths such as `/usr/lib` or `/usr/share` as the place where we look for the `brokers.d` folder to prevent being broken or not-well-working because of leftovers of configuration files.

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by jibel** [comment]
no plan to ship brokers as deb
