### ISSUE TITLE
Feature: Update Docs to include versions compatible

### ISSUE THREAD

**Issue by sgregorioTC** [ubuntu/authd#322]
### Is there an existing request for this feature?

- [X] I have searched the existing issues and found none that matched mine

### Describe the feature

The README.md does't specify what versions of Ubuntu these new authd features support. Am I able to install this on 20.04 LTS and be able to use OIDC auth providers or do I have to be on 24.04 to use it? Are some features compatible with some versions of Ubuntu and not others?

### Describe the ideal solution

I'd like to see a list of what this is compatible with.

### Environment
* authd version: please run //TODO
* Distribution: (**NAME** in `/etc/os-release`)
* Distribution version: (**VERSION_ID** on `/etc/os-release`):

### Log files
Please redact/remove sensitive information:
```raw
authd logs can be found in //TODO
```

### Application settings
Please redact/remove sensitive information:
```raw
You can get the configuration file from //TODO
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by jibel** [comment]
Thanks for your report.

[The documentation](https://github.com/ubuntu/authd/wiki/01---Get-started-with-authd) has been updated with the supported versions of Ubuntu (22.04 LTS and 24.04 LTS)

Do not hesitate to report any issue you may find.
