### ISSUE TITLE
Feature: Documentation 

### ISSUE THREAD

**Issue by kirkog86** [ubuntu/authd#327]
### Is there an existing request for this feature?

- [X] I have searched the existing issues and found none that matched mine

### Describe the feature

Please add step-by-step documentation on how to configure authd, as of now, you explained only how to install it...

### Environment
* authd version: please run //TODO
* Distribution: (**NAME** in `/etc/os-release`)
* Distribution version: (**VERSION_ID** on `/etc/os-release`):

### Log files
Please redact/remove sensitive information:
```raw
authd logs can be found in //TODO
```

### Application settings
Please redact/remove sensitive information:
```raw
You can get the configuration file from //TODO
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by sgregorioTC** [comment]
did the install work for you? When I run the install command on 24.04 it tells me unable to locate package

**Comment by drehelis** [comment]
@sgregorioTC see here: https://bugs.launchpad.net/ubuntu/+source/authd/+bug/2048781/comments/25

**Comment by suoko** [comment]
> @sgregorioTC see here: https://bugs.launchpad.net/ubuntu/+source/authd/+bug/2048781/comments/25
> 
> > We decided to remove the authd package in noble for the time being.
> > The current implementation (in particular the one in the PAM module) is not up to our standard in terms of quality and what we are confortable to support in the long term. Rather than releasing as is and having risky SRUs in the future changing a large part of the implementation, we decided against this and rather polishing the code, securing it, adding even more tests and releasing all that as a new package SRUed to the 24.04 LTS in the coming months.
> > That way, we won’t risk to regress any potential users and we will use an architecture we are more confortable supporting for the next 5/10 years of the LTS release.
> > It means that when we reintroduce it, we will rerequest a new MIR too as the PAM module will largely change and we want to ensure we follow the process and quality standard we expect for the Ubuntu distribution.

What about the previous method?
What I'm experiencing with https://github.com/ubuntu/aad-auth is that users can correctly join against AAD (using corporate email + AAD password), but I cannot see them in the entraID portal. How is that possible ?

**Comment by jibel** [comment]
Hi, documentation has been added to the [GitHub Wiki](https://github.com/ubuntu/authd/wiki) and the [contributing guide](https://github.com/ubuntu/authd/blob/main/CONTRIBUTING.md) has been updated too.
