### ISSUE TITLE
From aad-auth to authd: how to proceed ?

### ISSUE THREAD

**Issue by suoko** [ubuntu/authd#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

I have a machine upgraded from 22.04 (intune joined) to 23.10 (added the azure join) to 24.04.
I could see the logs from azure till beg of May, after that it's like it's not active anymore.
Has the old method stopped working for all or it just stopped for 24.04 ?
How do I proceed with this new authd and 24.04 ?

 

### Steps to reproduce it

Add the ppa https://launchpad.net/~ubuntu-desktop/+archive/ubuntu/ppa
Try to configure the tenant and appid somewhere

### Ubuntu users: System information and logs

.

### Environment
* authd version: please run //TODO
* Distribution: (**NAME** in `/etc/os-release`)
* Distribution version: (**VERSION_ID** on `/etc/os-release`):

### Log files
Please redact/remove sensitive information:
```raw
authd logs can be found in //TODO
```

### Application settings
Please redact/remove sensitive information:
```raw
You can get the configuration file from //TODO
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by RyanHecht** [comment]
With the recent launch of the test PPA and the [documentation](https://github.com/ubuntu/authd/wiki/02---Installation), I'd also love to get guidance on how best to migrate from aad-auth!

**Comment by jibel** [comment]
Thanks for your report. aad-auth and authd are two different implementation and you cannot directly migrate from the experimental implementation (aad-auth) based entirely on MSAL to authd which relies on OIDC and device code flow.

Do not hesitate to report a new issue if anything is unclear in the [documentation](https://github.com/ubuntu/authd/wiki)
