### ISSUE TITLE
Test in progress

### ISSUE THREAD

**Issue by suoko** [ubuntu/authd#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

I'm trying to run authd with the following steps

### Steps to reproduce it

Here are the steps to reproduce my tests on 24.04:

1) install golang 
2) git clone this repo and run "go build"
3) move authd to /usr/local/bin
4) create systemd service /etc/systemd/system/authd.service

```
[Unit]
Description=Azure Active Directory Authentication Daemon

[Service]
ExecStart=/usr/local/bin/authd
Restart=always

[Install]
WantedBy=multi-user.target
```

5) enable and start the service
6) create /etc/authd/config.yaml

```
tenant_id: "your-tenant-id"
client_id: "your-client-id"
client_secret: "your-client-secret"
```

### Environment
* authd version: from today's git
* Distribution: 2404
* Distributionversion: 24.04

### Log files
Please redact/remove sensitive information:
```
WARNING Skipping broker "config.yaml" is not correctly configured: can't create broker "config.yaml": dbus broker from configuration file: "/etc/authd/brokers.d/config.yaml": missing field for broker: error when getting key of section "authd": key "name" not exists 
ERROR can't create daemon: unexpected number of systemd socket activation (0 != 1)
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by jibel** [comment]
Thanks for your report and sorry for the delay of the response.

Since you tested authd we released binary builds in a PPA and the Snap store. You can refer to [the documentation](https://github.com/ubuntu/authd/wiki) for installation and configuration steps.

Do not hesitate to report any issue you may find.
