### ISSUE TITLE
"could not get user info" when user doesn't have an email

### ISSUE THREAD

**Issue by jibel** [ubuntu/authd#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

When the user does not have an email set, they cannot log in and it fails with an error: "could not get user info"

This error is not clear and should indicate the problem. There is not much risk of leaking information in this case, since the authentication is already happening.

### Steps to reproduce it

.

### Environment
* authd version: please run //TODO
* Distribution: (**NAME** in `/etc/os-release`)
* Distribution version: (**VERSION_ID** on `/etc/os-release`):

### Log files
Please redact/remove sensitive information:
```raw
authd logs can be found in //TODO
```

### Application settings
Please redact/remove sensitive information:
```raw
You can get the configuration file from //TODO
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by denisonbarbosa** [comment]
Fixed by https://github.com/ubuntu/oidc-broker/pull/31
