### ISSUE TITLE
“Gimme your password” needs to be renamed

### ISSUE THREAD

**Issue by jibel** [ubuntu/authd#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

“Gimme your password” needs to be renamed to "Enter your passphrase"

### Steps to reproduce it

.

### Environment
* authd version: please run //TODO
* Distribution: (**NAME** in `/etc/os-release`)
* Distribution version: (**VERSION_ID** on `/etc/os-release`):

### Log files
Please redact/remove sensitive information:
```raw
authd logs can be found in //TODO
```

### Application settings
Please redact/remove sensitive information:
```raw
You can get the configuration file from //TODO
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by denisonbarbosa** [comment]
This was fixed by https://github.com/ubuntu/oidc-broker/pull/30, so I'll mark it as completed.
