### ISSUE TITLE
Remove “Done” from QR code view in GDM

### ISSUE THREAD

**Issue by jibel** [ubuntu/authd#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

The QR code view in GDM must not display "Done" button but wait for the MFA confirmation instead.

### Steps to reproduce it

.

### Environment
* authd version: please run //TODO
* Distribution: (**NAME** in `/etc/os-release`)
* Distribution version: (**VERSION_ID** on `/etc/os-release`):

### Log files
Please redact/remove sensitive information:
```raw
authd logs can be found in //TODO
```

### Application settings
Please redact/remove sensitive information:
```raw
You can get the configuration file from //TODO
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by 3v1n0** [comment]
Closed in shell side too.
