### ISSUE TITLE
QR code in offline mode error message must be changed.

### ISSUE THREAD

**Issue by jibel** [ubuntu/authd#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

In offline authentication if the user selects QR code the error message is unclear, “could not generate QR code layout”.
The error message should be more descriptive since it is not possible to use the QR Code method offline

### Steps to reproduce it

.

### Environment
* authd version: please run //TODO
* Distribution: (**NAME** in `/etc/os-release`)
* Distribution version: (**VERSION_ID** on `/etc/os-release`):

### Log files
Please redact/remove sensitive information:
```raw
authd logs can be found in //TODO
```

### Application settings
Please redact/remove sensitive information:
```raw
You can get the configuration file from //TODO
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by denisonbarbosa** [comment]
Fixed by https://github.com/ubuntu/oidc-broker/pull/31
