### ISSUE TITLE
Only propose auth method available with current network state

### ISSUE THREAD

**Issue by jibel** [ubuntu/authd#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

We should track online/offline state and propose authentication methods compatible with the current state.
For instance, we should not propose a QR code auth while offline.

### Steps to reproduce it

.

### Environment
* authd version: please run //TODO
* Distribution: (**NAME** in `/etc/os-release`)
* Distribution version: (**VERSION_ID** on `/etc/os-release`):

### Log files
Please redact/remove sensitive information:
```raw
authd logs can be found in //TODO
```

### Application settings
Please redact/remove sensitive information:
```raw
You can get the configuration file from //TODO
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by denisonbarbosa** [comment]
This will be closed by https://github.com/ubuntu/oidc-broker/pull/37.
