### ISSUE TITLE
Search for broker configuration file also in a /var/snap/ readable paths

### ISSUE THREAD

**Issue by jibel** [ubuntu/authd#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

Currently the broker configuration must be copied manually to /etc/authd/, ideally it is searched in /var/snap readable paths.

### Steps to reproduce it

.

### Environment
* authd version: please run //TODO
* Distribution: (**NAME** in `/etc/os-release`)
* Distribution version: (**VERSION_ID** on `/etc/os-release`):

### Log files
Please redact/remove sensitive information:
```raw
authd logs can be found in //TODO
```

### Application settings
Please redact/remove sensitive information:
```raw
You can get the configuration file from //TODO
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by didrocks** [comment]
To amend: look rather at manual copy to /etc + make the broker readable.

**Comment by denisonbarbosa** [comment]
After we decided that the user would manually copy the configuration file, this is fixed by https://github.com/ubuntu/oidc-broker/pull/21
