### ISSUE TITLE
userdel/deluser must support deleting users from cache

### ISSUE THREAD

**Issue by jibel** [ubuntu/authd#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

userdel/deluser doesn’t work: the user is not /etc/passwd. We should look at integrating this.

### Steps to reproduce it

.

### Environment
* authd version: please run //TODO
* Distribution: (**NAME** in `/etc/os-release`)
* Distribution version: (**VERSION_ID** on `/etc/os-release`):

### Log files
Please redact/remove sensitive information:
```raw
authd logs can be found in //TODO
```

### Application settings
Please redact/remove sensitive information:
```raw
You can get the configuration file from //TODO
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by adombeck** [comment]
`userdel`/`deluser` are not aware of NSS sources, they only delete users from `/etc/passwd`. NSS doesn't seem to support deleting entries. Maybe we should ship our own command-line tool which supports deleting users from the authd cache. We could only consider patching `userdel`/`deluser` if we really want those to work with authd, but I'm not sure if that's necessary. Maybe documenting our own command-line tool is good enough.
