### ISSUE TITLE
Gdm: add support for regenerate

### ISSUE THREAD

**Issue by jibel** [ubuntu/authd#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

Gdm: add support to regenerate a QR code.

### Steps to reproduce it

.

### Environment
* authd version: please run //TODO
* Distribution: (**NAME** in `/etc/os-release`)
* Distribution version: (**VERSION_ID** on `/etc/os-release`):

### Log files
Please redact/remove sensitive information:
```raw
authd logs can be found in //TODO
```

### Application settings
Please redact/remove sensitive information:
```raw
You can get the configuration file from //TODO
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by 3v1n0** [comment]
Closed via #402 and #421
