### ISSUE TITLE
Issue: how to compile?

### ISSUE THREAD

**Issue by smabit** [ubuntu/authd#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

Are there any instructions on how to compile the code? I have tried with release 0.3 and main on Ubuntu 22.04 with go version go1.22.4 linux/amd64, but when running either go build or go install, it will only download dependencies but not compile anything stating that a main function is missing.

- [ ] 

### Steps to reproduce it

go build -v -a
internal/unsafeheader
internal/goarch
internal/cpu
internal/abi
internal/bytealg
internal/chacha8rand
internal/coverage/rtcov
internal/godebugs
internal/goexperiment
internal/goos
runtime/internal/atomic
runtime/internal/math
runtime/internal/sys
runtime/internal/syscall
internal/race
sync/atomic
runtime
internal/itoa
unicode
unicode/utf8
math/bits
math
cmp
slices
encoding
unicode/utf16
log/internal
internal/nettrace
container/list
crypto/internal/alias
crypto/subtle
crypto/internal/boring/sig
vendor/golang.org/x/crypto/cryptobyte/asn1
vendor/golang.org/x/crypto/internal/alias
google.golang.org/protobuf/internal/flags
google.golang.org/protobuf/internal/set
google.golang.org/grpc/serviceconfig
internal/reflectlite
sync
internal/testlog
internal/bisect
errors
sort
internal/oserror
syscall
io
bytes
strings
time
bufio
strconv
context
reflect
internal/syscall/unix
internal/poll
internal/safefilepath
internal/syscall/execenv
path
io/fs
os
hash
hash/crc32
html
internal/fmtsort
encoding/binary
fmt
encoding/base64
internal/godebug
path/filepath
regexp/syntax
compress/flate
compress/gzip
encoding/json
log
golang.org/x/net/internal/timeseries
regexp
net/url
text/template/parse
vendor/golang.org/x/net/dns/dnsmessage
internal/singleflight
internal/intern
net/netip
text/template
runtime/cgo
html/template
crypto
crypto/cipher
crypto/internal/boring
net
crypto/internal/randutil
math/rand
math/big
crypto/rand
crypto/aes
crypto/des
crypto/internal/edwards25519/field
crypto/internal/nistec/fiat
embed
crypto/internal/nistec
crypto/ecdh
crypto/elliptic
crypto/internal/bigmod
crypto/internal/boring/bbig
crypto/sha512
encoding/asn1
crypto/internal/edwards25519
vendor/golang.org/x/crypto/cryptobyte
crypto/ed25519
crypto/hmac
crypto/md5
crypto/rc4
crypto/rsa
crypto/ecdsa
crypto/sha1
crypto/sha256
crypto/dsa
encoding/hex
encoding/pem
vendor/golang.org/x/crypto/chacha20
crypto/x509/pkix
crypto/x509
vendor/golang.org/x/crypto/internal/poly1305
vendor/golang.org/x/sys/cpu
vendor/golang.org/x/crypto/chacha20poly1305
vendor/golang.org/x/crypto/hkdf
vendor/golang.org/x/text/transform
vendor/golang.org/x/text/unicode/bidi
vendor/golang.org/x/text/secure/bidirule
vendor/golang.org/x/text/unicode/norm
crypto/tls
vendor/golang.org/x/net/idna
net/textproto
vendor/golang.org/x/net/http/httpguts
vendor/golang.org/x/net/http/httpproxy
vendor/golang.org/x/net/http2/hpack
mime
mime/quotedprintable
mime/multipart
net/http/internal
net/http/internal/ascii
text/tabwriter
google.golang.org/grpc/backoff
golang.org/x/sys/unix
net/http/httptrace
net/http
google.golang.org/grpc/internal/grpclog
google.golang.org/grpc/grpclog
google.golang.org/grpc/connectivity
google.golang.org/grpc/attributes
google.golang.org/grpc/internal/credentials
hash/fnv
google.golang.org/protobuf/internal/detrand
google.golang.org/protobuf/internal/errors
google.golang.org/protobuf/encoding/protowire
google.golang.org/protobuf/internal/pragma
google.golang.org/protobuf/reflect/protoreflect
google.golang.org/protobuf/internal/encoding/messageset
google.golang.org/protobuf/internal/genid
google.golang.org/protobuf/internal/order
go/token
google.golang.org/protobuf/internal/strs
google.golang.org/protobuf/reflect/protoregistry
google.golang.org/protobuf/runtime/protoiface
google.golang.org/protobuf/proto
google.golang.org/protobuf/internal/descfmt
google.golang.org/protobuf/internal/descopts
google.golang.org/protobuf/internal/editiondefaults
google.golang.org/protobuf/internal/encoding/text
google.golang.org/protobuf/internal/encoding/defval
google.golang.org/protobuf/internal/filedesc
golang.org/x/net/trace
google.golang.org/protobuf/encoding/prototext
google.golang.org/protobuf/internal/encoding/tag
io/ioutil
google.golang.org/protobuf/internal/version
google.golang.org/grpc/internal
google.golang.org/protobuf/internal/impl
google.golang.org/grpc/metadata
google.golang.org/grpc/internal/grpcrand
google.golang.org/grpc/codes
google.golang.org/grpc/internal/envconfig
google.golang.org/grpc/internal/grpcutil
google.golang.org/grpc/encoding
google.golang.org/grpc/internal/backoff
google.golang.org/grpc/internal/balancerload
google.golang.org/grpc/internal/buffer
google.golang.org/grpc/internal/grpcsync
google.golang.org/grpc/internal/idle
google.golang.org/protobuf/internal/encoding/json
google.golang.org/protobuf/encoding/protojson
golang.org/x/text/transform
golang.org/x/text/unicode/bidi
golang.org/x/text/secure/bidirule
golang.org/x/text/unicode/norm
golang.org/x/net/idna
golang.org/x/net/http/httpguts
golang.org/x/net/http2/hpack
golang.org/x/net/http2
google.golang.org/protobuf/internal/filetype
google.golang.org/protobuf/runtime/protoimpl
google.golang.org/protobuf/protoadapt
google.golang.org/grpc/credentials
google.golang.org/grpc/internal/channelz
google.golang.org/grpc/channelz
google.golang.org/grpc/resolver
google.golang.org/grpc/balancer
google.golang.org/grpc/balancer/base
google.golang.org/grpc/balancer/roundrobin
google.golang.org/grpc/credentials/insecure
google.golang.org/grpc/encoding/proto
google.golang.org/grpc/internal/balancer/gracefulswitch
google.golang.org/protobuf/types/known/durationpb
google.golang.org/protobuf/types/known/timestamppb
google.golang.org/grpc/binarylog/grpc_binarylog_v1
google.golang.org/protobuf/types/known/anypb
google.golang.org/genproto/googleapis/rpc/status
google.golang.org/grpc/internal/status
google.golang.org/grpc/status
google.golang.org/grpc/internal/binarylog
google.golang.org/grpc/internal/metadata
google.golang.org/grpc/internal/pretty
google.golang.org/grpc/internal/serviceconfig
google.golang.org/grpc/internal/resolver
google.golang.org/grpc/internal/resolver/passthrough
google.golang.org/grpc/internal/transport/networktype
google.golang.org/grpc/internal/resolver/unix
google.golang.org/grpc/internal/syscall
google.golang.org/grpc/keepalive
google.golang.org/grpc/peer
google.golang.org/grpc/stats
google.golang.org/grpc/tap
net/http/httputil
google.golang.org/grpc/balancer/grpclb/state
google.golang.org/grpc/internal/resolver/dns/internal
google.golang.org/grpc/internal/resolver/dns
google.golang.org/grpc/resolver/dns
google.golang.org/grpc/internal/transport
google.golang.org/grpc
github.com/ubuntu/authd

### Environment
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by jhaar** [comment]
I have the same issue with Ubuntu-24.04 (OP with 22.04). Maybe you could publish releases to tide people over? What's really weird is this is under "/ubuntu", but "apt install authd" does not work/exist under Ubuntu-24.04?

May I say authd could be big... Being able to login with EntraID, Google, Okta creds - could really help get Ubuntu into enterprise (as well as home users).
