### ISSUE TITLE
Feature: documentation improvement

### ISSUE THREAD

**Issue by massigori** [ubuntu/authd#457]
### Is there an existing request for this feature?

- [X] I have searched the existing issues and found none that matched mine

### Describe the feature

Albeit complete, the project documentation implies a medium to high level of understanding of both Entra ID and Ubuntu.
I think the documentation should cater to all users and further highlight the server use case.   

### Describe the ideal solution

1. Split the documentation in server and desktop. While some of the steps are the same, the target user is likely to be different (especially when we add additional brokers). 
2. Related to the above, the usage section would benefit from SSH centric use case for servers 
3. If possible, oorganise the configuration section in a way that can accommodate additional brokers
4. Entra has updated the enterprise application page and the current screenshots are out of date. While regular users will understand what they need to do, novice users might be lost. I also think we should reference the Microsoft [documentation ]( https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-register-app?tabs=certificate)as much as possible
5. Consider including the group management section of the documentation in the Entra ID broker configuration, as there might be subtle differences between different brokers 
6. Add a sample cloud-init fil for automated deployments 
7. include an architecture diagram that explains how the solution interacts with the system components / cloud IDPs
As a longer term development point the documentation should be reorganised to follow the Diataxis framework 

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by khaffner** [comment]
I for one would like to know if authd with Entra ID gives any benefits/features after logging on to Ubuntu. 

Lots of us come from Windows, where logging on to the computer with an AD or EntraID account gives automatic access to file shares, automatic signin to Edge, Teams, etc.. That can easily be an expectation from an end user who just logged on to Ubuntu with their Entra ID.

I would very much like a section in the docs that say what problems authd solves, and what problems it does not solve.

**Comment by jibel** [comment]
@massigori , I added a reference to Microsoft documentation. However, I don't know what you mean with "updated enterprise application page". The screenshot is what I currently have on entra.microsoft.com.
I didn't show the left menu on purpose to save some horizontal space though.
Anyway, I added more detailled steps to register a new app.

**Comment by jibel** [comment]
A page has been added to cover the server/ssh case https://github.com/ubuntu/authd/wiki/05--SSH-access-to-a-server

**Comment by jibel** [comment]
All the major points have been addressed. I'm closing this issue. Do not hesitate to opne a new one for specific points.
