### ISSUE TITLE
Issue: First login not possible if using SSH

### ISSUE THREAD

**Issue by valluwtf** [ubuntu/authd#458]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

We are currently testing if authd is a valid option to manage access to (a lot of) virtual machines using Ubuntu-Server.

I have installed it following the Guide and both apps are working, which is great. When trying to log in for the first time with an Entra user via SSH, I just get "Connection closed" without anything else and the following line appears in /var/log/auth.log
"sshd[291699]: fatal: initgroups:  {{myusername}}@{{mydomain}} Invalid argument"
(sensitive information redacted)

Using the local terminal directly, I can successfully authenticate with my user using MFA and home directory is created, groups are set. 

I have configured the setting for ssh first login to allow the domains accordingly, but it doesn't seem to help.

### Where does the issue happens

- [ ] I can reproduce the issue in the graphical display manager
- [X] I can reproduce the issue on a terminal with "login"

### Steps to reproduce it

1. When using SSH to log in 
2. for the first time with a previously non-existent user (only existing in Entra)
3. login does not work

### Environment
* broker version: please run `snap info authd-msentraid`
``` name:      authd-msentraid
summary:   MSEntra ID broker for authd
publisher: Canonical✓ [...]
services:
  authd-msentraid: simple, enabled, active
snap-id:      vS3oJLMss6lgWwoFcPqYDUA2HB20I1Dc
tracking:     0.x/stable
refresh-date: 5 days ago, at 12:47 CEST
channels:
  0.x/stable:    0.1 2024-07-18 (10) 17MB -
  0.x/candidate: ↑
  0.x/beta:      ↑
  0.x/edge:      0.1 2024-08-07 (29) 17MB -
installed:       0.1            (10) 17MB
 ```

* authd version: please run `/usr/libexec/authd version`
```
authd   0.3.1~ppa4
```

* gnome shell version: please run `apt policy gnome-shell`
``` gnome-shell:
  Installed: (none)
  Candidate: 46.3.1-1ubuntu1~24.04.1 
```

* Distribution: (**NAME** in `/etc/os-release`)
```
Ubuntu
```

* Distribution version: (**VERSION_ID** on `/etc/os-release`):
```
24.04
```

### Log files
` /var/log/auth.log:`
```
"sshd[291699]: fatal: initgroups: {{username}}@{{domain}}: Invalid argument"
```

#### Authd entries:

```raw
journalctl -u authd.service
Aug 13 11:34:09 vs-052457 systemd[1]: Starting authd.service - Authd daemon service...
Aug 13 11:34:10 vs-052457 authd[293906]: INFO No configuration file: Config File "authd" Not Found in "[/ /etc/authd /usr/libexec]".
Aug 13 11:34:10 vs-052457 authd[293906]: We will only use the defaults, env variables or flags.
Aug 13 11:34:10 vs-052457 authd[293906]: DEBUG Debug mode is enabled
Aug 13 11:34:10 vs-052457 authd[293906]: DEBUG Building authd object
Aug 13 11:34:10 vs-052457 authd[293906]: DEBUG Building broker detection
Aug 13 11:34:10 vs-052457 authd[293906]: DEBUG Auto-detecting brokers
Aug 13 11:34:10 vs-052457 authd[293906]: DEBUG Loading broker "local"
Aug 13 11:34:10 vs-052457 authd[293906]: DEBUG Loading broker "msentraid.conf"
Aug 13 11:34:10 vs-052457 authd[293906]: DEBUG Dbus broker configuration at "/etc/authd/brokers.d/msentraid.conf"
Aug 13 11:34:10 vs-052457 authd[293906]: DEBUG Building new GRPC NSS service
Aug 13 11:34:10 vs-052457 authd[293906]: DEBUG Building new GRPC PAM service
Aug 13 11:34:10 vs-052457 authd[293906]: DEBUG Building new daemon
Aug 13 11:34:10 vs-052457 authd[293906]: DEBUG Use socket activation
Aug 13 11:34:10 vs-052457 authd[293906]: DEBUG Registering GRPC services
Aug 13 11:34:10 vs-052457 authd[293906]: DEBUG Starting to serve requests on /run/authd.sock
Aug 13 11:34:10 vs-052457 authd[293906]: DEBUG Ready state sent to systemd
Aug 13 11:34:10 vs-052457 authd[293906]: INFO Serving GRPC requests on /run/authd.sock
Aug 13 11:34:10 vs-052457 systemd[1]: Started authd.service - Authd daemon service.

```

####  MS Entra ID broker entries:

```raw
journalctl -u snap.authd-msentraid.authd-msentraid.service
Aug 13 11:34:19 vs-052457 systemd[1]: Stopping snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msentraid.authd-msentraid...
Aug 13 11:34:19 vs-052457 systemd[1]: snap.authd-msentraid.authd-msentraid.service: Deactivated successfully.
Aug 13 11:34:19 vs-052457 systemd[1]: Stopped snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msentraid.authd-msentraid.
Aug 13 11:34:19 vs-052457 systemd[1]: snap.authd-msentraid.authd-msentraid.service: Consumed 5.488s CPU time, 8.0M memory peak, 0B memory swap peak.
Aug 13 11:34:19 vs-052457 systemd[1]: Started snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msentraid.authd-msentraid.
Aug 13 11:34:19 vs-052457 authd-msentraid.authd-msentraid[293936]: time=2024-08-13T11:34:19.449+02:00 level=INFO msg="No configuration file: Config File \"authd-msentraid\" Not Found in \"[/var/snap/authd-msentraid/10 /root/snap/authd-msentraid/10 /etc/authd-msentraid /snap/authd-msentraid/10/bin]\".\nWe will only use the defaults, env variables or flags."
Aug 13 11:34:19 vs-052457 authd-msentraid.authd-msentraid[293936]: time=2024-08-13T11:34:19.449+02:00 level=DEBUG msg="Debug mode is enabled"
Aug 13 11:34:19 vs-052457 authd-msentraid.authd-msentraid[293936]: time=2024-08-13T11:34:19.692+02:00 level=DEBUG msg="Building new daemon"
Aug 13 11:34:19 vs-052457 authd-msentraid.authd-msentraid[293936]: time=2024-08-13T11:34:19.692+02:00 level=DEBUG msg="Starting to serve requests"
Aug 13 11:34:19 vs-052457 authd-msentraid.authd-msentraid[293936]: time=2024-08-13T11:34:19.692+02:00 level=INFO msg="Serving requests as com.ubuntu.authd.MSEntraID"

```

### Application settings

Please redact/remove sensitive information:

####  Broker configuration:

```raw
cat /var/snap/authd-msentraid/current/broker.conf
[oidc]
issuer = https://login.microsoftonline.com/{{ myIssuerID }}/v2.0
client_id = {{ myClientID }}

[users]
# The directory where the home directory will be created for new users.
# Existing users will keep their current directory.
# The user home directory will be created in the format of {home_base_dir}/{username}
home_base_dir = /home

# The username suffixes that are allowed to login via ssh without existing previously in the system.
# The suffixes must be separated by commas.
ssh_allowed_suffixes = {{ myDomain }}
```

####  Broker authd configuration:

```raw
cat /etc/authd/brokers.d/msentraid.conf
# This section is used by authd to identify and communicate with the broker.
# It should not be edited.
[authd]
name = Microsoft Entra ID
brand_icon = /snap/authd-msentraid/current/broker_icon.png
dbus_name = com.ubuntu.authd.MSEntraID
dbus_object = /com/ubuntu/authd/MSEntraID
```

### Relevant information

It seems like it cant find some relevant files 

INFO No configuration file: Config File "authd" Not Found in "[/ /etc/authd /usr/libexec]".
INFO msg="No configuration file: Config File \"authd-msentraid\" Not Found in \"[/var/snap/authd-msentraid/10 /root/snap/authd-msentraid/10 /etc/authd-msentraid /snap/authd-msentraid/10/bin]\".

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by denisonbarbosa** [comment]
Hey, @valluwtf! Thanks for reporting the issue!

We believe we already have those fixes in the current test release, but we have not promoted them to stable yet (still running some tests).

I'll let you know once they are available so you can retry this, ok?

**Comment by valluwtf** [comment]
Thanks, now on Edge channel/ppa with
msentraid: 0.1 2024-08-16 
authd:  0.3.2

it does something different but still doesn't work, sadly. 

I get from /var/log/auth.log:
pam_authd_exec(sshd:auth): conversation failed

and from authd
WARN rpc error: code = NotFound desc = user "{{ myUser }}@{{ myDomain }}" is not known by any broker

Local login still works though 👍 

I will wait for updates, I guess :)

**Comment by denisonbarbosa** [comment]
Hey, @valluwtf! Well, at least we got some progress...

> WARN rpc error: code = NotFound desc = user "{{ myUser }}@{{ myDomain }}" is not known by any broker

This error is returned if we can't precheck the user on the broker side. Would you mind taking a look at a couple things before we proceed?

1) Can you double-check the configuration file for the broker? The configuration file could have been reset after refreshing the snap and, just as a reminder, the values for the allowed suffixes are case-sensitive (i.e. `domain.com` != `DOMAIN.COM`).

2) Would mind also looking at `/etc/nsswitch.conf` to see if the authd NSS module is listed there?
You should have lines like:
```
passwd:         files systemd sss authd
group:          files systemd sss authd
shadow:         files systemd sss authd
```

**Comment by valluwtf** [comment]
I followed the new instructions for sshd config [here](https://github.com/ubuntu/authd/wiki/05--Accessing-a-server-over-SSH) and can now successfully log in a new user via ssh using authd! 👍 

(* Still experiencing issues with displaying the QR code in my Ubuntu 22.04 WSL, but with other versions and also when using local login in same WSL but on VM it does show, so it doesn't seem to be an issue with authd package. But if anyone has an idea how to show the qr image instead of the escape sequences, I would appreciate the help :) - it also doesn't show using Powershell or CMD, all on Windows11 OS)

These logs still persist, though:

 `authd[613161]: 2024/08/21 13:23:56 WARN rpc error: code = NotFound desc =`
coming every few minutes at least which is quite often, I guess.

And also whenever I use my regular ssh login (not authd) using private key or password I get this message.

`authd[613161]: 2024/08/21 13:24:15 WARN rpc error: code = InvalidArgument desc = no user name provided`

Regarding your ideas: 
1. everything is correct in broker config

2. this is nnsswitch.conf output:
```
passwd:         files systemd authd
group:          files systemd authd
shadow:         files systemd authd
gshadow:        files systemd
```

**Comment by denisonbarbosa** [comment]
Hey, @valluwtf. I'm glad you were able to make it work!

It's worth remembering that, while it does work, authd is not fully supported on Jammy (22.04) yet so that's why you see the issue with the QRCode rendering on instances of this version (we had to make some changes in GDM and those were not backported to Jammy yet).

Regarding the log message, we are [aware of the issue](https://github.com/ubuntu/authd/issues/468) and we'll work on it.

Since you were able to authenticate with SSH, I'm closing this issue as completed. Thanks for providing some feedback on this.
