### ISSUE TITLE
authd not automatically added as a source to nsswitch.conf when reinstalled

### ISSUE THREAD

**Issue by adombeck** [ubuntu/authd#459]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

Installing the `authd` package from `ppa:ubuntu-enterprise-desktop/authd-edge` does not add `authd` to the `passwd`, `group`, and `shadow` databases in `/etc/nsswitch.conf`.

### Where does the issue happens

- [ ] I can reproduce the issue in the graphical display manager
- [X] I can reproduce the issue on a terminal with "login"

### Steps to reproduce it

In Ubuntu 24.04:
1. `sudo add-apt-repository ppa:ubuntu-enterprise-desktop/authd-edge`
2. `sudo apt install authd`
3. `sudo apt remove authd`
4. `sudo apt install authd`
5. `cat /etc/nsswitch.conf`
6. See that `authd` is missing.

When trying to log in without the `authd` source in `/etc/nsswitch.conf`, it leads to the login failing with `Authentication failure` (when usind `sudo login` on the command-line). The journal shows:
```
pam_unix(login:account): could not identify user (from getpwnam($USER))
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by denisonbarbosa** [comment]
Just to complement: This only happens after authd is removed and installed back again. The first installation configures it correctly, but after we remove the package and install it again, the NSS module is not readded to `/etc/nsswitch.conf`.

**Comment by adombeck** [comment]
@denisonbarbosa Do you know how I can restore the system to a state where installing the package does add the NSS module?

**Comment by 3v1n0** [comment]
Just to be sure, we've to make sure that it gets removed on (removal? and) purge.

**Comment by adombeck** [comment]
Fixed by https://github.com/ubuntu/authd/pull/461
