### ISSUE TITLE
Issue: nil pointer exception in getGroups()

### ISSUE THREAD

**Issue by cobranovich** [ubuntu/authd#460]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

User authentication against our GCC-High tenant with two factor authentication fails and journalctl logs show a nil pointer exception in getGroups().

> Aug 14 09:18:41 mnlab3 authd-msentraid.authd-msentraid[2615045]: time=2024-08-14T09:18:41.224-05:00 level=DEBUG msg="Debug mode is enabled"
Aug 14 09:18:41 mnlab3 authd-msentraid.authd-msentraid[2615045]: time=2024-08-14T09:18:41.314-05:00 level=DEBUG msg="Building new daemon"
Aug 14 09:18:41 mnlab3 authd-msentraid.authd-msentraid[2615045]: time=2024-08-14T09:18:41.314-05:00 level=DEBUG msg="Starting to serve requests"
Aug 14 09:18:41 mnlab3 authd-msentraid.authd-msentraid[2615045]: time=2024-08-14T09:18:41.314-05:00 level=INFO msg="Serving requests as com.ubuntu.authd.MSEntraID"
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x129398d]
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: goroutine 131 [running]:
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: github.com/ubuntu/authd-oidc-brokers/internal/providers/msentraid.Provider.getGroups({}, 0xc000680ce0?)
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]:         /build/authd-msentraid/parts/broker/build/internal/providers/msentraid/msentraid.go:113 +0x32d
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: github.com/ubuntu/authd-oidc-brokers/internal/providers/msentraid.Provider.GetUserInfo({}, {0x0?, 0x0?}, 0xc000484780, 0x0?)
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]:         /build/authd-msentraid/parts/broker/build/internal/providers/msentraid/msentraid.go:49 +0xcc
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: github.com/ubuntu/authd-oidc-brokers/internal/broker.(*Broker).fetchUserInfo(0xc0003d4000, {0x17e9b68, 0xc0001cc000}, 0x0?, 0xc0001efbe0)
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]:         /build/authd-msentraid/parts/broker/build/internal/broker/broker.go:691 +0x271
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: github.com/ubuntu/authd-oidc-brokers/internal/broker.(*Broker).handleIsAuthenticated(0xc0003d4000, {0x17e9b68, 0xc0001cc000}, 0xc0002443c0, 0xc000510810?)
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]:         /build/authd-msentraid/parts/broker/build/internal/broker/broker.go:451 +0x908
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: github.com/ubuntu/authd-oidc-brokers/internal/broker.(*Broker).IsAuthenticated.func1()
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]:         /build/authd-msentraid/parts/broker/build/internal/broker/broker.go:380 +0x49
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: created by github.com/ubuntu/authd-oidc-brokers/internal/broker.(*Broker).IsAuthenticated in goroutine 130
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]:         /build/authd-msentraid/parts/broker/build/internal/broker/broker.go:379 +0x49e

The exception seems to be  line 113 in msentraid.go. I suspect 'm' is nil for some reason.
`	for _, obj := range m.GetValue() {`

In a separate PowerShell, the user indicates "TransitiveMemberOf()" works, but we may not be following the same API sequence used in authd-msentaid.

### Where does the issue happens

- [X] I can reproduce the issue in the graphical display manager
- [X] I can reproduce the issue on a terminal with "login"

### Steps to reproduce it

Primarily testing by running

> sudo login <<MY_USERNAME>>

and going through our two-factor log-in process.  Two-factor authentication seems to work correctly before the exception is reported. 

### Environment
* broker version: please run `snap info authd-msentraid`
```raw
name:      authd-msentraid
summary:   MSEntra ID broker for authd
publisher: Canonical✓
store-url: https://snapcraft.io/authd-msentraid
license:   GPL-3.0
description: |
  This is the MS Entra ID broker snap for authd  to provide MS Entra ID OIDC based authentication on
  Ubuntu with authd.
services:
  authd-msentraid: simple, enabled, active
snap-id:      vS3oJLMss6lgWwoFcPqYDUA2HB20I1Dc
tracking:     0.x/edge
refresh-date: yesterday at 17:38 CDT
channels:
  0.x/stable:    0.1 2024-07-18 (10) 17MB -
  0.x/candidate: ↑
  0.x/beta:      ↑
  0.x/edge:      0.1 2024-08-13 (30) 17MB -
installed:       0.1            (30) 17MB -
```

* authd version: please run `/usr/libexec/authd version`
```raw
authd	0.3.1~ppa4
```
* gnome shell version: please run `apt policy gnome-shell`
 ```raw 
gnome-shell:
  Installed: 46.3.1-1ubuntu1~24.04.1
  Candidate: 46.3.1-1ubuntu1~24.04.1
  Version table:
 *** 46.3.1-1ubuntu1~24.04.1 500
        500 https://ppa.launchpadcontent.net/ubuntu-enterprise-desktop/authd/ubuntu noble/main amd64 Packages
        100 /var/lib/dpkg/status
     46.0-0ubuntu6~24.04.1 500 (phased 0%)
        500 http://us.archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages
     46.0-0ubuntu5.1 500
        500 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages
     46.0-0ubuntu5 500
        500 http://us.archive.ubuntu.com/ubuntu noble/main amd64 Packages
```

* Distribution: (**NAME** in `/etc/os-release`)
```raw
UBUNUTU
```
* Distribution version: (**VERSION_ID** on `/etc/os-release`):
```raw
"24.04"
```
### Log files
Please redact/remove sensitive information:

#### Authd entries:

```raw
Aug 05 14:27:44 mnlab3 systemd[1]: Starting authd.service - Authd daemon service...
Aug 05 14:27:46 mnlab3 authd[1927]: INFO No configuration file: Config File "authd" Not Found in "[/ /et>
Aug 05 14:27:46 mnlab3 authd[1927]: We will only use the defaults, env variables or flags.
Aug 05 14:27:46 mnlab3 authd[1927]: DEBUG Debug mode is enabled
Aug 05 14:27:46 mnlab3 authd[1927]: DEBUG Building authd object
Aug 05 14:27:46 mnlab3 authd[1927]: DEBUG Building broker detection
Aug 05 14:27:46 mnlab3 authd[1927]: DEBUG Auto-detecting brokers
Aug 05 14:27:46 mnlab3 authd[1927]: DEBUG Loading broker "local"
Aug 05 14:27:46 mnlab3 authd[1927]: DEBUG Loading broker "msentraid.conf"
Aug 05 14:27:46 mnlab3 authd[1927]: DEBUG Dbus broker configuration at "/etc/authd/brokers.d/msentraid.c>
Aug 05 14:27:46 mnlab3 authd[1927]: DEBUG Building new GRPC NSS service
Aug 05 14:27:46 mnlab3 authd[1927]: DEBUG Building new GRPC PAM service
Aug 05 14:27:46 mnlab3 authd[1927]: DEBUG Building new daemon
Aug 05 14:27:46 mnlab3 authd[1927]: DEBUG Use socket activation
Aug 05 14:27:46 mnlab3 authd[1927]: DEBUG Registering GRPC services
Aug 05 14:27:46 mnlab3 authd[1927]: DEBUG Starting to serve requests on /run/authd.sock
Aug 05 14:27:46 mnlab3 authd[1927]: DEBUG Ready state sent to systemd
Aug 05 14:27:46 mnlab3 authd[1927]: INFO Serving GRPC requests on /run/authd.sock
Aug 05 14:27:46 mnlab3 systemd[1]: Started authd.service - Authd daemon service.
Aug 14 09:18:42 mnlab3 authd[1927]: DEBUG User "REDACTED" is unknown
```

####  MS Entra ID broker entries:

```raw
Aug 14 09:18:41 mnlab3 systemd[1]: snap.authd-msentraid.authd-msentraid.service: Scheduled restart job, restart counter is at 1.
Aug 14 09:18:41 mnlab3 systemd[1]: Started snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msentraid.authd-msentraid.
Aug 14 09:18:41 mnlab3 authd-msentraid.authd-msentraid[2615045]: time=2024-08-14T09:18:41.215-05:00 level=INFO msg="No configuration file: Config File \"authd-msen
traid\" Not Found in \"[/var/snap/authd-msentraid/30 /root/snap/authd-msentraid/30 /etc/authd-msentraid /snap/authd-msentraid/30/bin]\".\nWe will only use the defa
ults, env variables or flags."
Aug 14 09:18:41 mnlab3 authd-msentraid.authd-msentraid[2615045]: time=2024-08-14T09:18:41.224-05:00 level=DEBUG msg="Debug mode is enabled"
Aug 14 09:18:41 mnlab3 authd-msentraid.authd-msentraid[2615045]: time=2024-08-14T09:18:41.314-05:00 level=DEBUG msg="Building new daemon"
Aug 14 09:18:41 mnlab3 authd-msentraid.authd-msentraid[2615045]: time=2024-08-14T09:18:41.314-05:00 level=DEBUG msg="Starting to serve requests"
Aug 14 09:18:41 mnlab3 authd-msentraid.authd-msentraid[2615045]: time=2024-08-14T09:18:41.314-05:00 level=INFO msg="Serving requests as com.ubuntu.authd.MSEntraID"
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x129398d]
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: goroutine 131 [running]:
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: github.com/ubuntu/authd-oidc-brokers/internal/providers/msentraid.Provider.getGroups({}, 0xc000680ce0?)
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]:         /build/authd-msentraid/parts/broker/build/internal/providers/msentraid/msentraid.go:113 +0x32d
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: github.com/ubuntu/authd-oidc-brokers/internal/providers/msentraid.Provider.GetUserInfo({}, {0x0?, 0x0?}, 0xc000484780, 0x0?)
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]:         /build/authd-msentraid/parts/broker/build/internal/providers/msentraid/msentraid.go:49 +0xcc
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: github.com/ubuntu/authd-oidc-brokers/internal/broker.(*Broker).fetchUserInfo(0xc0003d4000, {0x17e9b68, 0xc0001cc000}, 0x0?, 0xc0001efbe0)
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]:         /build/authd-msentraid/parts/broker/build/internal/broker/broker.go:691 +0x271
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: github.com/ubuntu/authd-oidc-brokers/internal/broker.(*Broker).handleIsAuthenticated(0xc0003d4000, {0x17e9b68, 0xc0001cc000}, 0xc0002443c0, 0xc000510810?)
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]:         /build/authd-msentraid/parts/broker/build/internal/broker/broker.go:451 +0x908
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: github.com/ubuntu/authd-oidc-brokers/internal/broker.(*Broker).IsAuthenticated.func1()
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]:         /build/authd-msentraid/parts/broker/build/internal/broker/broker.go:380 +0x49
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]: created by github.com/ubuntu/authd-oidc-brokers/internal/broker.(*Broker).IsAuthenticated in gorou
tine 130
Aug 14 09:19:15 mnlab3 authd-msentraid.authd-msentraid[2615045]:         /build/authd-msentraid/parts/broker/build/internal/broker/broker.go:379 +0x49e
Aug 14 09:19:15 mnlab3 systemd[1]: snap.authd-msentraid.authd-msentraid.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 14 09:19:15 mnlab3 systemd[1]: snap.authd-msentraid.authd-msentraid.service: Failed with result 'exit-code'.
Aug 14 09:19:15 mnlab3 systemd[1]: snap.authd-msentraid.authd-msentraid.service: Scheduled restart job, restart counter is at 2.
```

### Application settings

Please redact/remove sensitive information:

####  Broker configuration:

```raw
[oidc]
issuer=https://login.microsoftonline.us/REDACTED/v2.0
client_id=REDACTED
[users]
# The directory where the home directory will be created for new users.
# Existing users will keep their current directory.
# The user home directory will be created in the format of {home_base_dir}/{username}
# home_base_dir = /home

# The username suffixes that are allowed to login via ssh without existing previously in the system.
# The suffixes must be separated by commas.
# ssh_allowed_suffixes = @REDACTED
```

####  Broker authd configuration:

```raw
# This section is used by authd to identify and communicate with the broker.
# It should not be edited.
[authd]
name = Microsoft Entra ID
brand_icon = /snap/authd-msentraid/current/broker_icon.png
dbus_name = com.ubuntu.authd.MSEntraID
dbus_object = /com/ubuntu/authd/MSEntraID
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by adombeck** [comment]
Fixed by https://github.com/ubuntu/authd-oidc-brokers/pull/108

**Comment by cobranovich** [comment]
Also posted [here](https://github.com/ubuntu/authd-oidc-brokers/pull/108), but just in case...

Can we re-open this? It looks like [this commit](https://github.com/ubuntu/authd-oidc-brokers/commit/c602d18a0a7f597430558f95f6308aefbb750855), removed the nil check and we are now seeing the same seg fault on the EntraID broker. It's not clear why TransitiveMemberOf() is not returning any groups for us. We are using a GCC HIGH tenant. So, perhaps I'll open another ticket if I can pin-point what's failing and report out.


> Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12ce8d4]
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]: goroutine 116 [running]:
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]: github.com/ubuntu/authd-oidc-brokers/internal/providers/msentraid.getAllUserGroups(0x1866818?)
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]:         /build/authd-msentraid/parts/broker/build/internal/providers/msentraid/msentraid.go:199 +0xb4
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]: github.com/ubuntu/authd-oidc-brokers/internal/providers/msentraid.Provider.getGroups({{0xc00023a180?, 0x1f?, 0xc0003d4690?}}, 0xc00022c620)
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]:         /build/authd-msentraid/parts/broker/build/internal/providers/msentraid/msentraid.go:156 +0x285
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]: github.com/ubuntu/authd-oidc-brokers/internal/providers/msentraid.Provider.GetUserInfo({{0xc00023a180?, 0x0?, 0x148d8a0?}}, {0x0?, 0x0?}, 0xc>
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]:         /build/authd-msentraid/parts/broker/build/internal/providers/msentraid/msentraid.go:96 +0x10b
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]: github.com/ubuntu/authd-oidc-brokers/internal/broker.(*Broker).fetchUserInfo(0xc000266600, {0x18623c0, 0xc000476000}, 0xc000197250?, 0xc0003a>
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]:         /build/authd-msentraid/parts/broker/build/internal/broker/broker.go:777 +0x1b1
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]: github.com/ubuntu/authd-oidc-brokers/internal/broker.(*Broker).handleIsAuthenticated(0xc000266600, {0x18623c0, 0xc000476000}, 0xc0001fc000, 0>
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]:         /build/authd-msentraid/parts/broker/build/internal/broker/broker.go:530 +0x14e5
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]: github.com/ubuntu/authd-oidc-brokers/internal/broker.(*Broker).IsAuthenticated.func1()
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]:         /build/authd-msentraid/parts/broker/build/internal/broker/broker.go:449 +0x49
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]: created by github.com/ubuntu/authd-oidc-brokers/internal/broker.(*Broker).IsAuthenticated in goroutine 115
Dec 09 12:02:20 mnlab3 authd-msentraid.authd-msentraid[54490]:         /build/authd-msentraid/parts/broker/build/internal/broker/broker.go:448 +0x48f
