### ISSUE TITLE
Issue: incorrect file specified in the documentation and other issues

### ISSUE THREAD

**Issue by jcoffi-ghlabs** [ubuntu/authd#477]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

The documentation refers to /etc/logins.def but the file is /etc/login.defs on a brand new install of 24.04 desktop. Also, it [says to configure the registered app like the photo](https://github.com/ubuntu/authd/wiki/03---Configuration#:~:text=And%20configure%20it%20as%20follow%3A): But we don't know what to put for the reply URL.

### Where does the issue happens

- [ ] I can reproduce the issue in the graphical display manager
- [ ] I can reproduce the issue on a terminal with "login"

### Steps to reproduce it

Read the documentation and try to follow the steps.

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by jibel** [comment]
Thanks for your report.

I fixed the position of the 's' in `login.defs` and we will have a look at the second issue.

**Comment by jibel** [comment]
Regarding your second question about the redirect url, we are using the [OAuth 2.0 device code flow](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-device-code) and a redirect URI is not needed. You can read more about redirect URI in [Microsoft documentation](https://learn.microsoft.com/en-us/entra/identity-platform/reply-url#should-i-add-a-redirect-uri-to-an-app-registration).

However, you have a good point, we'll update the screenshot to not show any redirect URI.

**Comment by jcoffi-ghlabs** [comment]
The picture shows it's there and the instructions imply you should match the picture. It should probably be updated.

**Comment by jibel** [comment]
The picture has been updated to not show any redirect URI.
