### ISSUE TITLE
Logging in over SSH with a different user exposes the username

### ISSUE THREAD

**Issue by jibel** [ubuntu/authd#478]
authd_msentraid: 0.x/edge:      0.1 2024-08-20 (32)

## Test Case
1. Configure allowed_suffix in authd
2. SSH with a random user
3. On the external device, authenticate with a valid user

## Expected result
Login is denied

## Actual result
The identity of the valid user is revealed in the logs:

![image](https://github.com/user-attachments/assets/ea2e3bca-5cae-440a-9fb5-8a825977be90)

**Comment by denisonbarbosa** [comment]
This was fixed by [authd-oidc-brokers#115](https://github.com/ubuntu/authd-oidc-brokers/pull/115).
