### ISSUE TITLE
Errors in GDM disappear too quickly

### ISSUE THREAD

**Issue by jibel** [ubuntu/authd#479]
When an error occur during logging in GDM, it disappear too quickly and is almost impossible to read.

**Comment by denisonbarbosa** [comment]
@3v1n0 had mentioned this in the last testing session that we had. IIRC, this is a limitation from GDM itself, but he probably can give us a better input on this.

**Comment by 3v1n0** [comment]
This is handled via https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3466 & https://salsa.debian.org/gnome-team/gnome-shell/-/commit/f3f1db35cda8a99b761835c71f431ecbb59ca5cd
