### ISSUE TITLE
Add rate limiting to code renewal

### ISSUE THREAD

**Issue by jibel** [ubuntu/authd#480]
## Test Case
1. Login in text mode (e.g. use `sudo login`)
2. When the QR code is displayed, select "New QR code" and the `Enter`key pressed

## Expected result
New codes are provided

## Actual result
After a while, the UI stops responding and an error is displayed

![image](https://github.com/user-attachments/assets/35ad22cf-5eaa-43b9-9f33-6d646a33d4a6)

**Comment by 3v1n0** [comment]
Closed via f3fb9ec228b4a06e934c4c9c39d2a8ac705b03c8
