### ISSUE TITLE
Ubuntu-24.04.1 LTS successfully installs but unable to load after shutdown

### ISSUE THREAD

**Issue by kushalShukla-web** [ubuntu/authd#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

When installing Ubuntu it successfully installs.
After install it prompts an error, stating to report the developers that some error occured.
Still it works fine. But later after shutdown down when turned on again
It blinks creating media_ and keeps blinking with Ipv4 check and then Ipv6. And creating media_ keeps blinking

### System information and logs

Unable to run this after shutdown down

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by jibel** [comment]
Thanks for your report.

The issue you reported is not related to authd but the Ubuntu distribution. Please report a bug on Launchpad using https://bugs.launchpad.net/ubuntu/+filebug
