### ISSUE TITLE
Issue: UID range overlaps with those used by distros and systemd

### ISSUE THREAD

**Issue by nbraud** [ubuntu/authd#547]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

`authd` assigns UIDs in the range [63000; 2³¹[ which overlaps with those used by:
- [Debian], which reserves the range [60000; 65000[ for use by the distro; I couldn't check Ubuntu's own policy manual, as the link [in the wiki] is broken, but it is derived from Debian's and likely uses the same range;
- systemd's [`DynamicUser`] feature allocates in [61184; 2¹⁶ - 16[

The simplest way to resolve this would be to use [2¹⁶; 2³¹[ as `authd`'s UID range.

[Debian]: https://www.debian.org/doc/debian-policy/ch-opersys.html#uid-and-gid-classes
[in the wiki]: https://wiki.ubuntu.com/UbuntuDevelopment
[`DynamicUser`]: https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#DynamicUser=

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by adombeck** [comment]
Thanks for the report. We're working on a fix in #548.
