### ISSUE TITLE
Issue: Removing user / reset database

### ISSUE THREAD

**Issue by Patrock** [ubuntu/authd#550]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

Is there a command to remove a user (so the new creation causes changes in the home configuration to grasp) or completly reset the databases with all users and groups ?

After testing this tool i want to start from scratch.

thx

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by adombeck** [comment]
Hi, thanks for reaching out.

> Is there a command to remove a user (so the new creation causes changes in the home configuration to grasp) 

Not yet, but this is on our roadmap!

> or completly reset the databases with all users and groups ?

That's possible by deleting the cache directories and restarting the services:

```
sudo rm -rf /var/cache/authd/ && sudo rm -r /var/snap/authd-msentraid/current/cache && sudo snap restart authd-msentraid && sudo systemctl restart authd
```

**Comment by Patrock** [comment]
okay, thx,  completly resetting did work...

Thx for this service
