### ISSUE TITLE
Feature: ARM64 support

### ISSUE THREAD

**Issue by sgregorioTC** [ubuntu/authd#573]
### Is there an existing request for this feature?

- [X] I have searched the existing issues and found none that matched mine

### Describe the feature

Trying to install on an arm64 version of 24.04 and getting an error from snap that the authd-msentraid package is not available on the architecture.

### Describe the ideal solution

Ideally both ARM64 and AMD64 are supported as platforms.

### Environment
* broker version: can't install
* authd version: 0.3.5~24.04
* gnome shell version: 46.3.1-1ubuntu~24.04.1
* Distribution: Ubuntu
* Distribution version: 24.04.0 LTS

command: sudo snap install authd-msentraid
error: snap "authd-msentraid" is not available on this architecture (arm64) but
       exists on other architectures (amd64).

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by didrocks** [comment]
Hey,

we can release it. Just be aware that we don’t have hardware right now to have those tested throughfully contrary to the amd64 version.

**Comment by didrocks** [comment]
You should have now an arm64 version of the snap available in the stable snap track.

Keep us posted that everything is fine for you there! Just be aware again that this architecture has very limited testing.

**Comment by didrocks** [comment]
Let’s not call that supported yet until we have more feedback :)

**Comment by didrocks** [comment]
Sounds good! Closing this one then. Thanks!
