### ISSUE TITLE
Also refresh non-expired token during login (when not in offline mode)

### ISSUE THREAD

**Issue by adombeck** [ubuntu/authd#614]
As explained in [this code comment](https://github.com/ubuntu/authd-oidc-brokers/blob/main/internal/broker/broker.go#L691-L695), we should ideally always refresh the token during login when online, not only when the token is expired. We didn't see a way to do that with the `golang.org/x/oauth2` package, but I found one now:

We can set the token expiry date to a date in the past before calling `oauth2.Config.TokenSource`:

```go
cachedInfo.Token.Expiry = time.Now().Add(-time.Hour)
tok, err := session.authCfg.oauth.TokenSource(timeoutCtx, cachedInfo.Token).Token()
```

**Comment by shiv-tyagi** [comment]
Hi @adombeck! Can you please assign this to me? I am new here and I really want to contribute to the project. This issue seems to be a good issue to start with. 

Thanks in advance!

**Comment by adombeck** [comment]
@shiv-tyagi Sure, thanks for taking the initiative! :)

**Comment by shiv-tyagi** [comment]
@adombeck  Thanks! Just a small question! I read the docs to setup the development environment. I could not figure out how to get a ms entra id test environment for development. Does do you do the testing? Is there any work around for that?

**Comment by adombeck** [comment]
You need a Microsoft Entra tenant. I found [this documentation](https://learn.microsoft.com/en-us/entra/verified-id/how-to-create-a-free-developer-account#create-a-microsoft-entra-tenant-for-development) on how to set up a free Microsoft Entra tenant for development, but I didn't try it out.

**Comment by shiv-tyagi** [comment]
I managed to get an Entra tenant. Thanks for your help. I have created a PR. Please let me know the steps ahead. Really happy to submit my first PR involving functional changes to authd. 🤩
