### ISSUE TITLE
Issue: Example broker state is not reset

### ISSUE THREAD

**Issue by didrocks** [ubuntu/authd#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

When reusing the same user like (user-needs-reset, user-can-reset or user-mfa), some state is kept on the broker side and lead to invalid flow.

### Steps to reproduce it

1. user-needs-reset or user-can-reset:
   a. Start the PAM binary, press escape, change user to one of the above
   b. Log in once with password
   c. Then, change your password on the newpasswd screen
   d. Restart a PAM session (do not restart authd), reselect the same user
  -> you are directly directed to the newpasswd screen

2. user-mfa:
Similarly, reusing the same user without restart authd can lead to different flows, some not proposing the "Give me your password screen", but directly topt and then via email link (requested twice).

Those 2 issues are probably related.

I suggest once fix to have a long live authd daemon, and try multiple scenarios, stopping as soon as something don’t feel right in the logic flow.

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by denisonbarbosa** [comment]
This issue was fixed by #74 and #67.
