### ISSUE TITLE
Document how to use network file systems (NFS, Samba) with ID mapping

### ISSUE THREAD

**Issue by adombeck** [ubuntu/authd#653]
We decided to go ahead with the fix for https://github.com/ubuntu/authd/issues/509 which generates unique random UIDs and GIDs. That affects the usage of network file systems on systems that use authd, because the same user will have different UIDs on different machines. We want to document how to circumvent the permission issues caused by that by using ID mapping with Samba and NFS + Kerberos.

**Comment by dekiesel** [comment]
Thank you for your work!

Can I already use authd if I only plan to use my account on one single ubuntu workstation.

My main use case is to get Azure Files (Samba) working so that I can access our company files.

Or should I rather wait for the documentation anyway?

**Comment by adombeck** [comment]
> Can I already use authd if I only plan to use my account on one single ubuntu workstation.
> 
> My main use case is to get Azure Files (Samba) working so that I can access our company files.

Sure, you can already try to get Samba to work. You can now also preview the documentation from the (unreviewed) PR here: https://github.com/ubuntu/authd/blob/653-document-id-mapping/docs/howto/use-with-samba.md
